server:
  port: 22046
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
    port-header: X-Forwarded-Port
    max-connections: 3000
    max-threads: 3000
spring:
  freemarker:
    template-loader-path: classpath:/templates/
    content-type: text/html
    suffix: .html
  datasource:
    url: jdbc:postgresql://192.168.4.18:25432/deng_yjm?stringtype=unspecified  #正式
    username: postgres
    password: Deng-2511582
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    druid:
      initial-size: 50
      max-active: 1000
      min-idle: 50
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 100000
      validation-query: select 'x'
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      log-abandoned: true
  kafka:
    listener:
      ack-count: 6
    bootstrap-servers: 19.15.26.34:9000 # 指定kafka代理地址
    consumer:
      enable-auto-commit: false
      auto-commit-interval: 1000
      group-id: logs-consumer-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      properties:
#        sasl.mechanism: PLAIN
#        security.protocol: SASL_PLAINTEXT
#        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="devlogs" password="zcdldevlogspassword";
#        connections.max.idle.ms: -1
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
